"use client"

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider, signOut,useSession } from "next-auth/react";
import NavBar from "@/components/nav";
import Sidebar from "@/components/sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// export const metadata = {
  //   title: "Create Next App",
  //   description: "Generated by create next app",
  // };
  
  export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <SessionProvider>
        <>
        <div className="mt-4">
      <NavBar/>
      </div>
        <div className="flex h-screen">

  <aside className="w-[15%] h-screen bg-gray-300 fixed top-0 left-0">
    <div className="h-full px-3 py-4 overflow-y-auto">
      <ul className="space-y-2 font-medium">

<Sidebar/>
      </ul>
    </div>
  </aside>

  <main className="flex-1 ml-[15%] p-4 bg-gray-100">
  
        {children}
  
  </main>
</div>
        </>
        </SessionProvider>
      </body>
    </html>
  );
}
